locked_images:
  - postgres:16.6-alpine
  - postgres:17-alpine
  - redis:7.4-alpine
  - orthancteam/orthanc:25.12.3

local_images:
  - dockerfile: tapirx.Dockerfile
    tag: tapirx:local
  - dockerfile: replay.Dockerfile
    tag: replay:local

login_required_images:
  - virtalabsinc/blueflow:testbed-3.0.5
  - upgrade/dev-viper:0.1.1